### ISSUE TITLE
edit email

### ISSUE THREAD

**Issue by rockdrigo** [te-online/code#1]
how i can edit the welcome email??? 
and personalize the email

thanks

**Comment by te-online** [comment]
@rockdrigo Wow, this one is **old** and I never saw it until now – must have missed the notification.
Hope you got it working in two years time :wink:

Note that the WordPress-Plugin which resides in this repository (Don't ask! :alien:) was originally created by Andreas Baumgartner. All that the plugin does, is resending the WordPress default welcome email to the selected user/s.

However, you can – of course – change the WordPress default welcome email.
This plugin should help https://wordpress.org/plugins/welcome-email-editor/

:beer:
